### ISSUE TITLE
Default tags provided in config are not available against measurment

### ISSUE THREAD

**Issue by logicnow-john** [AppOptics/statsd-appoptics-backend#1]
When using this library we provided extra tags in the config.js provided to it:
`{
    appoptics: {
            token: process.env.TOKEN ,
            source: process.env.SOURCE ,
            email: process.env.EMAIL ,
            tags: {region: process.env.SOME_REGION, environment: process.env.SOME_ENVIRONMENT}`

When debugging we noticed that these tags are not available against the metric and that instead they are just sent up as part of the payload and not appended to the metric tags.

DEBUG: Sending Payload: {"time":1552382940,"tags":{"region":"johns","environment":"MAC","host":"fe7640dfb7df"},"measurements":[{"name":"deploys.test.myservice","value":1,"tags":{"source":"johntest"}}]}

Is there a reason that these tags are not combined with the metric tags so they are available to filter through the AppOptics dashboard tags for that metric?

**Comment by mheffner** [comment]
@logicnow-john Yeah, I believe this was an oversight and those tags *should* be included into the per-measurement tags. @mbeale were you looking at this?

**Comment by mbeale** [comment]
@mheffner The reason this happens is that this is the default behavior for the API.  If we wanted to change that, should we create a config flag to not break any existing users?  If not, the PR lgtm

https://github.com/appoptics/statsd-appoptics-backend/pull/2

**Comment by mheffner** [comment]
@mbeale Right, I think we decided the API behavior wasn't the best fit for this. +1 for adding flag (opt-in?) to keep default behavior, and/or bump the minor version.

**Comment by mbeale** [comment]
new config option of mergeGlobalTags will cover this
